import type { User, DailyChallenge, Game, Offer, Product, LeaderboardEntry } from './types';
import { getImage } from './placeholder-images';
import { Star, Video, Gamepad2, Gift, Trophy, Crown, Coins as CoinsIcon } from 'lucide-react';
import React from 'react';

export const currentUser: User = {
  name: 'Alex',
  avatarUrl: getImage('userAvatar1').imageUrl,
  coins: 12580,
  isVip: false,
};

export const dailyChallenges: DailyChallenge[] = [
    {
        id: 1,
        title: 'First Spin',
        description: 'Use your first spin of the day.',
        reward: 20,
        isCompleted: true,
        progress: 100,
        currentValue: 1,
        targetValue: 1,
        difficulty: 'Easy',
        icon: React.createElement(Star),
    },
    {
        id: 2,
        title: 'Ad Marathon',
        description: 'Watch 5 video ads.',
        reward: 20,
        isCompleted: false,
        progress: 60,
        currentValue: 3,
        targetValue: 5,
        difficulty: 'Easy',
        icon: React.createElement(Video),
    },
    {
        id: 3,
        title: 'Game Starter',
        description: 'Play 10 game sessions.',
        reward: 10,
        isCompleted: false,
        progress: 20,
        currentValue: 2,
        targetValue: 10,
        difficulty: 'Easy',
        icon: React.createElement(Gamepad2),
    },
    {
        id: 4,
        title: 'Spin Master',
        description: 'Spin the wheel 5 times.',
        reward: 30,
        isCompleted: false,
        progress: 20,
        currentValue: 1,
        targetValue: 5,
        difficulty: 'Medium',
        icon: React.createElement(Gift),
    },
    {
        id: 5,
        title: 'Game Enthusiast',
        description: 'Play 30 game sessions.',
        reward: 25,
        isCompleted: false,
        progress: 33,
        currentValue: 10,
        targetValue: 30,
        difficulty: 'Medium',
        icon: React.createElement(Gamepad2),
    },
    {
        id: 6,
        title: 'Coin Collector',
        description: 'Win a total of 100 coins from spins.',
        reward: 75,
        isCompleted: false,
        progress: 20,
        currentValue: 20,
        targetValue: 100,
        difficulty: 'Medium',
        icon: React.createElement(CoinsIcon),
    },
    {
        id: 7,
        title: 'Game Legend',
        description: 'Play 50 game sessions in one day.',
        reward: 50,
        isCompleted: false,
        progress: 4,
        currentValue: 2,
        targetValue: 50,
        difficulty: 'Hard',
        icon: React.createElement(Trophy),
    },
    {
        id: 8,
        title: 'VIP Spinner',
        description: 'Spin the wheel 10 times.',
        reward: 250,
        isCompleted: false,
        isVip: true,
        progress: 0,
        currentValue: 0,
        targetValue: 10,
        difficulty: 'Hard',
        icon: React.createElement(Trophy),
    },
    {
        id: 9,
        title: 'Jackpot Hunter',
        description: 'Win a prize of Epic rarity or higher from the Spin Wheel.',
        reward: 100,
        isCompleted: false,
        isVip: true,
        progress: 0,
        currentValue: 0,
        targetValue: 1,
        difficulty: 'Hard',
        icon: React.createElement(Crown),
    },
];

export const games: Game[] = [
  { id: 'g1', title: 'Galaxy Invaders', provider: 'Playgama', reward: 50, ...getImage('game1'), iframeUrl: 'https://playgama.com/game/1' },
  { id: 'g2', title: 'Jungle Run', provider: 'Playgama', reward: 40, ...getImage('game2'), iframeUrl: 'https://playgama.com/game/2' },
  { id: 'g3', title: 'Puzzle Blocks', provider: 'Playgama', reward: 60, ...getImage('game3'), iframeUrl: 'https://playgama.com/game/3' },
  { id: 'g4', title: 'Speed Racer', provider: 'Playgama', reward: 75, ...getImage('game4'), iframeUrl: 'https://playgama.com/game/4' },
  { id: 'g5', title: 'Pirate\'s Treasure', provider: 'Playgama', reward: 55, ...getImage('game5'), iframeUrl: 'https://playgama.com/game/5' },
  { id: 'g6', title: 'Castle Defense', provider: 'Playgama', reward: 80, ...getImage('game6'), iframeUrl: 'https://playgama.com/game/6' },
];

export const offers: Offer[] = [
  { id: 'o1', title: 'Complete a Survey', company: 'Survey Junkie', reward: 1200, ...getImage('offer1') },
  { id: 'o2', title: 'Reach Level 10', company: 'RAID: Shadow Legends', reward: 5500, ...getImage('offer2') },
  { id: 'o3', title: 'Sign up and get cashback', company: 'Cashback App', reward: 800, ...getImage('offer3') },
  { id: 'o4', title: 'Install and create a budget', company: 'Finance Tracker', reward: 1500, ...getImage('offer4') },
];

export const products: Product[] = [
  { id: 'p1', name: 'Wireless Earbuds', description: 'High-fidelity sound on the go.', price: 15000, ...getImage('product1') },
  { id: 'p2', name: 'Smartwatch Series 8', description: 'Track your fitness and notifications.', price: 45000, ...getImage('product2') },
  { id: 'p3', name: 'RGB Gaming Mouse', description: 'Precision and customizable lighting.', price: 8000, ...getImage('product3') },
  { id: 'p4', name: 'Mechanical Keyboard', description: 'Tactile feedback for pro gamers.', price: 12000, ...getImage('product4') },
  { id: 'p5', name: '10,000mAh Power Bank', description: 'Charge your devices anywhere.', price: 6000, ...getImage('product5') },
  { id: 'p6', name: 'Pro VR Headset', description: 'Immerse yourself in virtual worlds.', price: 65000, ...getImage('product6') },
];

export const leaderboard: LeaderboardEntry[] = [
  { rank: 1, user: { name: 'Sophia', avatarUrl: getImage('leaderboardUser1').imageUrl }, score: 154200 },
  { rank: 2, user: { name: 'Jacob', avatarUrl: getImage('leaderboardUser2').imageUrl }, score: 149300 },
  { rank: 3, user: { name: 'CurrentUser', avatarUrl: currentUser.avatarUrl }, score: 125800 },
  { rank: 4, user: { name: 'Emily', avatarUrl: getImage('leaderboardUser3').imageUrl }, score: 110500 },
  { rank: 5, user: { name: 'Michael', avatarUrl: 'https://picsum.photos/seed/leader4/100/100' }, score: 98600 },
  { rank: 6, user: { name: 'Jessica', avatarUrl: 'https://picsum.photos/seed/leader5/100/100' }, score: 95400 },
  { rank: 7, user: { name: 'David', avatarUrl: 'https://picsum.photos/seed/leader6/100/100' }, score: 89300 },
  { rank: 8, user: { name: 'Sarah', avatarUrl: 'https://picsum.photos/seed/leader7/100/100' }, score: 82100 },
];
