import type { User, DailyChallenge, Game, Offer, Product } from './types';
import { getImage } from './placeholder-images';
import { Star, Video, Gamepad2, Gift, Trophy, Crown, Coins as CoinsIcon } from 'lucide-react';
import React from 'react';

export const currentUser: User = {
  name: 'Alex',
  avatarUrl: getImage('userAvatar1').imageUrl,
  coins: 12580,
  isVip: false,
};

export const dailyChallenges: DailyChallenge[] = [
    {
        id: 1,
        title: 'First Spin',
        description: 'Use your first spin of the day.',
        reward: 20,
        isCompleted: true,
        progress: 100,
        currentValue: 1,
        targetValue: 1,
        difficulty: 'Easy',
        icon: React.createElement(Star),
    },
    {
        id: 2,
        title: 'Ad Marathon',
        description: 'Watch 5 video ads.',
        reward: 20,
        isCompleted: false,
        progress: 60,
        currentValue: 3,
        targetValue: 5,
        difficulty: 'Easy',
        icon: React.createElement(Video),
    },
    {
        id: 3,
        title: 'Game Starter',
        description: 'Play 10 game sessions.',
        reward: 10,
        isCompleted: false,
        progress: 20,
        currentValue: 2,
        targetValue: 10,
        difficulty: 'Easy',
        icon: React.createElement(Gamepad2),
    },
    {
        id: 4,
        title: 'Spin Master',
        description: 'Spin the wheel 5 times.',
        reward: 30,
        isCompleted: false,
        progress: 20,
        currentValue: 1,
        targetValue: 5,
        difficulty: 'Medium',
        icon: React.createElement(Gift),
    },
    {
        id: 5,
        title: 'Game Enthusiast',
        description: 'Play 30 game sessions.',
        reward: 25,
        isCompleted: false,
        progress: 33,
        currentValue: 10,
        targetValue: 30,
        difficulty: 'Medium',
        icon: React.createElement(Gamepad2),
    },
    {
        id: 6,
        title: 'Coin Collector',
        description: 'Win a total of 100 coins from spins.',
        reward: 75,
        isCompleted: false,
        progress: 20,
        currentValue: 20,
        targetValue: 100,
        difficulty: 'Medium',
        icon: React.createElement(CoinsIcon),
    },
    {
        id: 7,
        title: 'Game Legend',
        description: 'Play 50 game sessions in one day.',
        reward: 50,
        isCompleted: false,
        progress: 4,
        currentValue: 2,
        targetValue: 50,
        difficulty: 'Hard',
        icon: React.createElement(Trophy),
    },
    {
        id: 8,
        title: 'VIP Spinner',
        description: 'Spin the wheel 10 times.',
        reward: 250,
        isCompleted: false,
        isVip: true,
        progress: 0,
        currentValue: 0,
        targetValue: 10,
        difficulty: 'Hard',
        icon: React.createElement(Trophy),
    },
    {
        id: 9,
        title: 'Jackpot Hunter',
        description: 'Win a prize of Epic rarity or higher from the Spin Wheel.',
        reward: 100,
        isCompleted: false,
        isVip: true,
        progress: 0,
        currentValue: 0,
        targetValue: 1,
        difficulty: 'Hard',
        icon: React.createElement(Crown),
    },
];

export const games: Game[] = [
  { id: 'g1', title: 'Galaxy Invaders', description: 'Classic space shooter', imageUrl: 'https://picsum.photos/seed/g1/400/500', imageHint: 'space arcade', iframeUrl: 'https://playgama.com/game/1', reward: 5 },
  { id: 'g2', title: 'Jungle Run', description: 'Endless runner adventure', imageUrl: 'https://picsum.photos/seed/g2/400/500', imageHint: 'jungle runner', iframeUrl: 'https://playgama.com/game/2', reward: 5 },
  { id: 'g3', title: 'Puzzle Blocks', description: 'Addictive block puzzle', imageUrl: 'https://picsum.photos/seed/g3/400/500', imageHint: 'colorful blocks', iframeUrl: 'https://playgama.com/game/3', reward: 5 },
  { id: 'g4', title: 'Speed Racer', description: 'High-speed racing game', imageUrl: 'https://picsum.photos/seed/g4/400/500', imageHint: 'racing car', iframeUrl: 'https://playgama.com/game/4', reward: 5 },
  { id: 'g5', title: 'Pirate\'s Treasure', description: 'Solve puzzles for loot', imageUrl: 'https://picsum.photos/seed/g5/400/500', imageHint: 'treasure chest', iframeUrl: 'https://playgama.com/game/5', reward: 5 },
  { id: 'g6', title: 'Castle Defense', description: 'Defend your kingdom', imageUrl: 'https://picsum.photos/seed/g6/400/500', imageHint: 'fantasy castle', iframeUrl: 'https://playgama.com/game/6', reward: 5 },
];

export const offers: Offer[] = [
  { id: 'o1', title: 'Complete a Survey', company: 'Survey Junkie', reward: 1200, ...getImage('offer1'), link: '#' },
  { id: 'o2', title: 'Reach Level 10', company: 'RAID: Shadow Legends', reward: 5500, ...getImage('offer2'), link: '#' },
  { id: 'o3', title: 'Sign up and get cashback', company: 'Cashback App', reward: 800, ...getImage('offer3'), link: '#' },
  { id: 'o4', title: 'Install and create a budget', company: 'Finance Tracker', reward: 1500, ...getImage('offer4'), link: '#' },
];

export const products: Product[] = [
  { id: 'p1', name: 'Wireless Earbuds', description: 'High-fidelity sound on the go.', price: 15000, ...getImage('product1') },
  { id: 'p2', name: 'Smartwatch Series 8', description: 'Track your fitness and notifications.', price: 45000, ...getImage('product2') },
  { id: 'p3', name: 'RGB Gaming Mouse', description: 'Precision and customizable lighting.', price: 8000, ...getImage('product3') },
  { id: 'p4', name: 'Mechanical Keyboard', description: 'Tactile feedback for pro gamers.', price: 12000, ...getImage('product4') },
  { id: 'p5', name: '10,000mAh Power Bank', description: 'Charge your devices anywhere.', price: 6000, ...getImage('product5') },
  { id: 'p6', name: 'Pro VR Headset', description: 'Immerse yourself in virtual worlds.', price: 65000, ...getImage('product6') },
];
